spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: consulta-service
          uri: lb://CONSULTA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/consulta/**
        - id: javamail
          uri: lb://JAVAMAIL
          filters:
            - StripPrefix=1
          predicates:
            - Path=/javamail/**
        - id: usuario-service
          uri: lb://USUARIO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/usuario/**
        - id: prescricao-service
          uri: lb://PRESCRICAO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/prescricao/**


server:
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
    instance-id:
      ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/