spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: consulta-service
          uri: lb://CONSULTA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/consulta/**

server:
  port: 9999

eureka:
  instance:
    instance-id:
      ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/