spring:
  application:
    name: CONSULTA-SERVICE
  datasource:
    url: jdbc:h2:mem:consulta
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  rabbitmq:
    host: RABBIT-SERVER
    port: 5672

eureka:
  instance:
    prefer-ip-address: true
    instance-id:
      ${spring.application.name}:${random.value}
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://EUREKA-SERVER:8761/eureka

app:
  myport: 8081

server:
  port: ${app.myport}

